apiVersion: apps/v1
kind: Deployment
metadata:
  name: am-service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: am-service2
  template:
    metadata:
      labels:
        app: am-service2
    spec:
      containers:
      - name: service2
        image: hashicorp/http-echo:0.2.3
        args: ["-text=service2 OK"]
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: am-service2
spec:
  ports:
    - port: 5678
      targetPort: 5678
  selector:
    app: am-service2
